name: Tests
on:
- push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install pip~=22.1
        python -m pip install -e '.[test]'
    - name: pytest
      run: pytest --cov --cov-report=term-missing
    - name: mypy
      run: |
        mypy palabras --ignore-missing-imports